[package]
name = "mixos-rdinit"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.98"
libc = "0.2.174"
log = { version = "0.4.27", features = ["std"] }
